# Generated by Django 4.2.5 on 2023-11-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findaway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Painting', 'Painting'), ('Cooking', 'Cooking'), ('Hiking', 'Hiking'), ('Gardening', 'Gardening'), ('Photography', 'Photography'), ('Playing Musical Instruments', 'Playing Musical Instruments'), ('Dancing', 'Dancing'), ('Traveling', 'Traveling'), ('Fishing', 'Fishing'), ('Knitting or Crocheting', 'Knitting or Crocheting'), ('Playing Sports', 'Playing Sports'), ('Bird Watching', 'Bird Watching'), ('Yoga', 'Yoga'), ('Playing Board Games', 'Playing Board Games'), ('Writing', 'Writing'), ('Collecting', 'Collecting'), ('DIY (Do-It-Yourself) Projects', 'DIY (Do-It-Yourself) Projects'), ('Meditation', 'Meditation'), ('Camping', 'Camping')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='zodiac',
            field=models.CharField(blank=True, choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=100),
        ),
    ]
